//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "hourly_weather")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub time_utc: DateTime,
    pub wmo_code: i32,
    #[sea_orm(column_type = "Float")]
    pub temperature_actual: f32,
    #[sea_orm(column_type = "Float")]
    pub temperature_apparent: f32,
    #[sea_orm(column_type = "Float")]
    pub relative_humidity: f32,
    #[sea_orm(column_type = "Float")]
    pub dew_point: f32,
    #[sea_orm(column_type = "Float")]
    pub surface_pressure: f32,
    #[sea_orm(column_type = "Float")]
    pub cloud_cover: f32,
    #[sea_orm(column_type = "Float")]
    pub cloud_cover_low: f32,
    #[sea_orm(column_type = "Float")]
    pub cloud_cover_mid: f32,
    #[sea_orm(column_type = "Float")]
    pub cloud_cover_high: f32,
    #[sea_orm(column_type = "Float")]
    pub wind_speed: f32,
    #[sea_orm(column_type = "Float")]
    pub max_wind_speed: f32,
    #[sea_orm(column_type = "Float")]
    pub wind_direction: f32,
    #[sea_orm(column_type = "Double")]
    pub total_precipitation: f64,
    #[sea_orm(column_type = "Float")]
    pub precipitation_probability: f32,
    #[sea_orm(column_type = "Double")]
    pub rain: f64,
    #[sea_orm(column_type = "Double")]
    pub snowfall: f64,
    #[sea_orm(column_type = "Double")]
    pub snow_depth: f64,
    #[sea_orm(column_type = "Double")]
    pub showers: f64,
    #[sea_orm(column_type = "Double")]
    pub visibility: f64,
    #[sea_orm(column_type = "Float")]
    pub shortwave_radiation: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
